apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-10-02T14:05:25Z"
  generation: 1
  labels:
    k8s-app: movie-web
  name: movie-web
  namespace: default
  resourceVersion: "33908"
  uid: b0ddc130-aef2-44c3-8717-44a441e69566
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: movie-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: movie-web
      name: movie-web
    spec:
      containers:
      - image: localhost:5000/movie-web
        imagePullPolicy: Always
        name: movie-web
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-02T14:05:25Z"
    lastUpdateTime: "2023-10-02T14:10:15Z"
    message: ReplicaSet "movie-web-59874bd4d5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-10-02T14:55:33Z"
    lastUpdateTime: "2023-10-02T14:55:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
